version: '3'
services:
  authserver:
    image: brighthive/authserver:latest
    environment:
      - APP_ENV=PRODUCTION
      - PG_USER='bh_authserver'
      - PG_PASSWORD='1qaz@WSX3edc'
      - PG_HOSTNAME=postgres
      - PG_DB=authserver
      - PG_PORT=5434
    ports:
      - 8000:8000